import React from 'react';
import { GameState } from '../game/engine';
import { TINY_UI } from '../game/premiumPixelArt';
import { TINY_SEMANTIC_UI } from '../game/tinyUiAssets';

const weaponName={warrior:'Wächterschwert',mage:'Runenfokus',archer:'Waldläuferbogen'} as const;
const weaponIcon={warrior:TINY_SEMANTIC_UI.attack,mage:TINY_SEMANTIC_UI.magic,archer:TINY_SEMANTIC_UI.arrow} as const;

export function InventoryPanel({gameState:g,onClose}:{gameState:GameState;onClose:()=>void}){
  const p=g.player,potions=g.items.filter(i=>i.itemType==='potion').length,shards=g.items.filter(i=>i.itemType==='xp_orb').length;
  const Slot=({label,src,empty=false}:{label:string;src?:string;empty?:boolean})=><div className="relative aspect-square border border-[#806039]/60 bg-black/45"><span className="absolute inset-x-1 bottom-1 z-10 truncate text-center text-[7px] font-black text-[#e8d3a2]/75">{label}</span>{src&&<img src={src} alt="" className="absolute inset-[18%] h-[54%] w-[64%] object-contain [image-rendering:pixelated]"/>}{empty&&<img src={TINY_SEMANTIC_UI.locked} alt="" className="absolute inset-[30%] h-[32%] w-[40%] object-contain opacity-35 [image-rendering:pixelated]"/>}</div>;
  return <div className="fixed inset-0 z-[70] overflow-y-auto bg-[#090704]/96 p-4 text-[#f5e4bc] pt-[max(1rem,env(safe-area-inset-top))]" style={{touchAction:'auto'}} data-ui-control><header className="mb-4 flex items-center justify-between"><div><small className="tracking-[.3em] text-[#c99d52]">DUNGEON VEIL</small><h2 className="font-serif text-2xl tracking-widest">INVENTAR</h2></div><button onClick={onClose} className="relative h-10 w-10"><img src={TINY_UI.squareButtonRed} alt="" className="absolute inset-0 h-full w-full [image-rendering:pixelated]"/><b className="relative text-white">X</b></button></header><div className="grid grid-cols-[124px_1fr] gap-3"><section className="rounded border border-[#795a31] bg-black/55 p-2"><b className="text-[9px] tracking-widest text-[#d8b56d]">AUSRÜSTUNG</b><div className="mt-2 grid grid-cols-2 gap-1"><Slot label="WAFFE" src={weaponIcon[p.playerClass]}/><Slot label="RÜSTUNG" empty/><Slot label="HELM" empty/><Slot label="HANDSCHUH" empty/><Slot label="STIEFEL" empty/><Slot label="RING" empty/></div></section><section className="rounded border border-[#795a31] bg-black/55 p-2"><b className="text-[9px] tracking-widest text-[#d8b56d]">RUCKSACK</b><div className="mt-2 space-y-2"><div className="border border-[#8b6a39]/45 bg-black/40 p-2"><div className="flex items-center gap-2"><img src={weaponIcon[p.playerClass]} alt="" className="h-8 w-8 object-contain [image-rendering:pixelated]"/><div><b className="block text-[11px] text-[#f2d08a]">{weaponName[p.playerClass]}</b><span className="text-[8px] text-white/45">AUSGERÜSTET</span></div></div></div><div className="grid grid-cols-2 gap-1 text-center text-[9px]"><div className="border border-[#46684a]/50 bg-black/40 p-2"><img src={TINY_SEMANTIC_UI.heal} alt="" className="mx-auto h-7 w-7 [image-rendering:pixelated]"/><b>Heilbeute</b><span className="block text-white/45">in Nähe {potions}</span></div><div className="border border-[#8a6b38]/50 bg-black/40 p-2"><span className="mx-auto block text-2xl text-[#ffd45d]">◆</span><b>Schleierbeute</b><span className="block text-white/45">in Nähe {shards}</span></div></div><p className="text-[9px] leading-relaxed text-white/42">Nur echte vorhandene Ausrüstung wird angezeigt. Leere Slots bleiben leer statt mit falschen Juwel- oder Blatt-Symbolen gefüllt zu werden.</p></div></section></div><div className="mt-3 grid grid-cols-3 rounded border border-[#795a31] bg-black/55 p-3 text-center text-xs"><b>ATK {p.attack}</b><b>DEF {p.defense}</b><b>SPD {p.speed}</b></div></div>}
